const alpha = (hex, opacity) => {
  const value = String(hex || '').replace('#', '');
  if (value.length !== 6) return hex;
  const r = parseInt(value.slice(0, 2), 16);
  const g = parseInt(value.slice(2, 4), 16);
  const b = parseInt(value.slice(4, 6), 16);
  return `rgba(${r},${g},${b},${opacity})`;
};

const createTheme = (base) => ({
  ...base,
  card: base.surfaceContainerLowest,
  cardBorder: base.border,
  text: base.onSurface,
  textSec: base.onSurfaceVariant,
  textTri: base.outline,
  accent: base.tertiaryContainer,
  gold: base.primaryContainer,
  danger: base.error,
  success: base.success,
  tabBar: alpha(base.surfaceContainerLowest, 0.94),
  tabActive: base.primary,
  tabInactive: base.outline,
  overlay: alpha(base.onSurface, 0.55),
  modal: base.surface,
  inputBg: base.surfaceContainerLow,
  inputBorder: alpha(base.primary, 0.15),
  gradientStart: base.primary,
  gradientEnd: base.primaryContainer,
  pageBgSoft: base.surfaceContainerLow,
  pageBgAlt: base.surfaceContainer,
  pageCard: base.surfaceContainerLowest,
  floatCard: alpha(base.surfaceContainerLowest, 0.94),
  subtleTint: alpha(base.primaryContainer, 0.12),
  subtleTintStrong: alpha(base.primaryContainer, 0.18),
  activeTint: alpha(base.primary, 0.16),
  accentLine: alpha(base.primary, 0.28),
  avatarBg: base.primaryFixed,
  warmNeutral: base.secondaryContainer,
  softOverlay: alpha(base.onSurface, 0.18),
  shadow: {
    shadowColor: base.shadowColor,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
});

const THEME_MAP = {
  default: createTheme({
    id: 'default',
    labelZh: '暖杏奶油',
    labelEn: 'Warm Apricot Cream',
    bg: '#FFF8EA',
    surface: '#FFFDF7',
    surfaceDim: '#E7DECD',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#FAF3E4',
    surfaceContainer: '#F4EBDD',
    surfaceContainerHigh: '#EEE1D0',
    surfaceContainerHighest: '#E7D8C4',
    primary: '#A86424',
    primaryContainer: '#F0AF45',
    primaryFixed: '#FFE4C6',
    primaryFixedDim: '#FFC781',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#5D3208',
    onPrimaryFixed: '#2F1600',
    tertiary: '#8F471C',
    tertiaryContainer: '#FF9861',
    tertiaryFixed: '#FFD9C4',
    onTertiary: '#FFFFFF',
    secondary: '#766250',
    secondaryContainer: '#EFE2CC',
    secondaryFixed: '#F4E7D1',
    onSurface: '#2E241B',
    onSurfaceVariant: '#726154',
    onBackground: '#2E241B',
    outline: '#9B8776',
    outlineVariant: '#E3D0BD',
    error: '#C25A46',
    errorContainer: '#FFE1DA',
    success: '#5A9E6F',
    border: 'rgba(168,100,36,0.13)',
    borderActive: 'rgba(168,100,36,0.34)',
    borderDashed: 'rgba(168,100,36,0.2)',
    shadowColor: '#A86424',
  }),
  sage: createTheme({
    id: 'sage',
    labelZh: '鼠尾草',
    labelEn: 'Sage',
    bg: '#F4FAF1',
    surface: '#FBFFFA',
    surfaceDim: '#D9E4D7',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#EEF6EC',
    surfaceContainer: '#E5F0E2',
    surfaceContainerHigh: '#DCE9DA',
    surfaceContainerHighest: '#D3E2D1',
    primary: '#557A52',
    primaryContainer: '#88B869',
    primaryFixed: '#DBF0D2',
    primaryFixedDim: '#B7D99C',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#233B21',
    onPrimaryFixed: '#132312',
    tertiary: '#3F6558',
    tertiaryContainer: '#78B9A0',
    tertiaryFixed: '#D2F0E5',
    onTertiary: '#FFFFFF',
    secondary: '#637267',
    secondaryContainer: '#E0EBDD',
    secondaryFixed: '#EAF3E7',
    onSurface: '#223026',
    onSurfaceVariant: '#5E6F62',
    onBackground: '#223026',
    outline: '#839486',
    outlineVariant: '#D1DED2',
    error: '#B4574A',
    errorContainer: '#FFE2DD',
    success: '#5F9F77',
    border: 'rgba(85,122,82,0.13)',
    borderActive: 'rgba(85,122,82,0.34)',
    borderDashed: 'rgba(85,122,82,0.2)',
    shadowColor: '#557A52',
  }),
  sunset: createTheme({
    id: 'sunset',
    labelZh: '落日果茶',
    labelEn: 'Sunset Fruit Tea',
    bg: '#FFF4EC',
    surface: '#FFFDFC',
    surfaceDim: '#EADCD4',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#FFF2E8',
    surfaceContainer: '#FBE7DB',
    surfaceContainerHigh: '#F4DCCC',
    surfaceContainerHighest: '#EDD1BF',
    primary: '#C05A38',
    primaryContainer: '#F0A24D',
    primaryFixed: '#FFD9C8',
    primaryFixedDim: '#FFB694',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#612613',
    onPrimaryFixed: '#321208',
    tertiary: '#A64E2D',
    tertiaryContainer: '#FF8F66',
    tertiaryFixed: '#FFD8CC',
    onTertiary: '#FFFFFF',
    secondary: '#7D6458',
    secondaryContainer: '#F1DDD2',
    secondaryFixed: '#F7E7DE',
    onSurface: '#31231D',
    onSurfaceVariant: '#78635A',
    onBackground: '#31231D',
    outline: '#A18476',
    outlineVariant: '#E7CDBF',
    error: '#C55A4A',
    errorContainer: '#FFE2DC',
    success: '#669B77',
    border: 'rgba(192,90,56,0.13)',
    borderActive: 'rgba(192,90,56,0.34)',
    borderDashed: 'rgba(192,90,56,0.22)',
    shadowColor: '#C05A38',
  }),
};

export const THEME_OPTIONS = Object.values(THEME_MAP).map(theme => ({
  id: theme.id,
  labelZh: theme.labelZh,
  labelEn: theme.labelEn,
  primary: theme.primary,
  secondary: theme.primaryContainer,
  background: theme.bg,
}));

export const getThemePalette = (themeId = 'default') => THEME_MAP[themeId] || THEME_MAP.default;

export const C = { ...getThemePalette('default') };

export const applyTheme = (themeId = 'default') => {
  const next = getThemePalette(themeId);
  Object.keys(C).forEach((key) => {
    delete C[key];
  });
  Object.assign(C, next);
  return C;
};

